before:
  hooks:
    - go mod vendor
builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  - name: "{{ .ProjectName }}"
    github:
      owner: tanelmae
      name: homebrew-brew

    url_template: "http://github.com/tanelmae/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: tanelmae
      email: tanel.mae@gmail.com

    folder: Formula

    homepage: "https://github.com/tanelmae/{{ .ProjectName }}"

    description: "Tool for generating NATS TLS keys and certificates"

    test: |
      system "#{bin}/{{ .ProjectName }} -v"
