before:
  hooks:
    - go mod vendor
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  - name: nats-tls
    github:
      owner: tanelmae
      name: homebrew-brew

    url_template: "http://github.com/tanelmae/nats-tls/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: tanelmae
      email: tanel.mae@gmail.com

    folder: Formula

    homepage: "https://github.com/tanelmae/nats-tls"

    description: "Tool for generating NATS TLS keys and certificates"

    test: |
      system "#{bin}/nats-tls -v"
